[package]
name = "grep-fre"
version = "0.1.0"
description = "Use the FRE portable runtime with ripgrep's matcher interface"
license = "Unlicense OR MIT"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
fre = { path = "../../../fre/crates/fre", default-features = false }
grep-matcher = { version = "0.1.8", path = "../matcher" }
grep-regex = { version = "0.1.14", path = "../regex" }
regex-syntax = "0.8.0"

[dev-dependencies]
grep-printer = { version = "0.3.1", path = "../printer" }
grep-searcher = { version = "0.1.17", path = "../searcher" }
